apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000 
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry-pod
      labels:
        app: registry
    spec:
      containers:
      - name: docker-registry
        image: registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
        - name: htpasswd
          mountPath: /auth
          readOnly: true
        - name: storage
          mountPath: /var/lib/registry
      volumes:
      - name: config
        configMap:
          name: docker-registry
          items:
          - key: registry-config.yml
            path: config.yml
      - name: htpasswd
        secret:
          secretName: docker-registry
          items:
          - key: HTPASSWD
            path: htpasswd
      - name: storage
        emptyDir: {}
