apiVersion: v1
kind: Service
metadata:
  name: tacos
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: tacos
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacos-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacos
  template:
    metadata:
      name: taco-pod
      labels:
        app: tacos
    spec:
      containers:
      - name: taco-container
        image: registry.zachandrews.com/tacos
        ports:
        - containerPort: 5000
