apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pi-chapter-certificate
  namespace: default
spec:
  dnsNames:
    - pi.zachandrews.com
  secretName: pi-chapter-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
